---
title: "Task 1 - Sierra Amphibians"
author: "Deanna Elliott"
date: "1/18/2022"
output: html_document
---

```{r setup, include=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(patchwork)
```

# Overview



# Read In Data

```{r}

amp <- readxl::read_xlsx(here("data", "sierra_amphibians.xlsx"))
```

# Wrangling

```{r ramu stage wrangling}

stage_count <- amp %>% 
  filter(amphibian_species == "RAMU",
         amphibian_life_stage %in% c("Tadpole", "SubAdult", "Adult")) %>% 
  mutate(survey_date = ymd(survey_date),
         year = year(survey_date)) %>% 
  group_by(year, amphibian_life_stage) %>% 
  summarize(count = n())
```

```{r ramu lake wrangling}

lake_counts <- amp %>% 
  filter(amphibian_species == "RAMU",
         amphibian_life_stage %in% c("SubAdult", "Adult")) %>% 
  mutate(survey_date = ymd(survey_date),
         year = year(survey_date)) %>% 
  group_by(lake_id) %>% 
  summarize(count = n())


top_5 <- lake_counts %>% 
  arrange(desc(count)) %>% 
  slice_head(n=5) %>% 
   mutate(lake_id = case_when(
    lake_id == "50183" ~ "Lake 50183",
    lake_id == "70583" ~ "Lake 70583", 
    lake_id == "50219" ~ "Lake 50219",
    lake_id == "41322" ~ "Lake 41322",
    lake_id == "10226" ~ "Lake 10226"))
```

# Plots

```{r plot counts by life stage}

p1 <- ggplot(data = stage_count,
       aes(x = as.factor(year), y = count, fill = amphibian_life_stage)) +
  geom_col(color = "black") +
  scale_fill_manual(values = c("goldenrod1", "steelblue3", "olivedrab3")) +
  labs(x = "Year", y = "Count", fill = "Life Stage") +
  theme_minimal()

p1
```

**Figure 1.** Caption

```{r counts by lake}

p2 <- ggplot(data = top_5,
       aes(x = count, y = lake_id, fill = lake_id)) +
  aes(y = reorder(lake_id, count)) +
  geom_col(color = "black") +
  scale_fill_manual(values = c("chocolate1", "orange", "gold1",
                                "sandybrown", "tan1")) +
  labs(x = "Count", y = "Location") +
  theme_minimal() +
  theme(legend.position = "none")

p2
```

**Figure 2.** Caption

# Combine Plots

```{r combine}

p1 / p2
```

**Figure 3.**

# Data Citation